# 随机端口设置
server:
  port: 0

# 服务应用名称
spring:
  application:
    name: eureka-producer

# 注册中心地址
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int[10000,19999]}    # 随机数配置实例ID
