server:
  port: 0
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IsResultXaL/SpringCloud-Greenwich.SR1/    # 配置git仓库的地址
          search-paths: spring-cloud-config-git/config-repo                 # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 774750747@qq.com                                        # git仓库的账号
          password: kang13640955236

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int[10000,19999]}    # 随机数配置实例ID
